### ISSUE TITLE
Duplicate key org.jacoco.core.internal.diff.MethodInfo

### ISSUE THREAD

**Issue by nicklasyao** [fang-yan-peng/diff-jacoco#6]
java.lang.IllegalStateException: Duplicate key org.jacoco.core.internal.diff.MethodInfo@897e99c
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1254)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jacoco.core.internal.diff.ClassInfo.setMethodInfos(ClassInfo.java:105)
        at org.jacoco.core.internal.diff.ASTGenerator.getClassInfo(ASTGenerator.java:159)
        at org.jacoco.core.internal.diff.CodeDiff.prepareDiffMethod(CodeDiff.java:331)
        at org.jacoco.core.internal.diff.CodeDiff.lambda$batchPrepareDiffMethod$1(CodeDiff.java:291)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zhuxt2015** [comment]
遇到同样的问题, 
`java.lang.IllegalStateException: Duplicate key org.jacoco.core.internal.diff.MethodInfo@798069fa
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1254)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jacoco.core.internal.diff.ClassInfo.setMethodInfos(ClassInfo.java:105)
        at org.jacoco.core.internal.diff.ASTGenerator.getClassInfo(ASTGenerator.java:159)
        at org.jacoco.core.internal.diff.CodeDiff.prepareDiffMethod(CodeDiff.java:331)
        at org.jacoco.core.internal.diff.CodeDiff.lambda$batchPrepareDiffMethod$1(CodeDiff.java:291)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by diduweiwu** [comment]
我也遇到同样问题了，函数名相同，参数不同，就GG了，作者大佬有考虑修复下吗？

**Comment by fang-yan-peng** [comment]
好滴 我修复一下

**Comment by fang-yan-peng** [comment]
已解决
